--- #YAML:1.0
name:               WWW-Wookie
version:            0.02
abstract:           Apache Wookie Connector Framework implementation
author:
    - Roland van Ipenburg <ipenburg@xs4all.nl>
license:            apache
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:        0.81
    Test::NoWarnings:  0
requires:
    Exception::Class:     0
    HTTP::Headers:        0
    HTTP::Request:        0
    HTTP::Request::Common:  0
    HTTP::Status:         0
    Log::Log4perl:        0
    LWP::UserAgent:       0
    Moose:                0
    Moose::Role:          0
    Moose::Util::TypeConstraints:  0
    MooseX::AttributeHelpers:  0
    namespace::autoclean:  0
    Readonly:             0
    Regexp::Common:       0
    URI:                  0
    XML::Simple:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
